## name: Forest
## author: anaidyss
## license: MIT
## dominant colors: green #a6e3a1, teal #59c2a5, amber #e3c078
## base: dark forest green #131a16, errors: terracotta #c9745c

selection_foreground    #e0ece2
selection_background    #2c3f34

background              #131a16
foreground              #cddbd0

# black
color0                  #1d2721
color8                  #4f6157
# red (terracotta, only for errors/critical)
color1                  #c9745c
color9                  #d99a82
# green (dominant #1)
color2                  #7cb87a
color10                 #a6e3a1
# yellow (amber, dominant #3)
color3                  #d9b36a
color11                 #e3c078
# blue (muted conifer blue-green)
color4                  #5f9790
color12                 #7fb8ad
# magenta (dusty mossy lilac, rarely used)
color5                  #a48bb5
color13                 #c2a8cf
# cyan (teal, dominant #2)
color6                  #4aa892
color14                 #6fd0b3
# white
color7                  #b9c7bb
color15                 #e0ece2

cursor                  #a6e3a1
cursor_text_color       #131a16

url_color               #59c2a5

bell_border_color       #e3c078

# START_AUTOGENERATED_TAB_STYLE
# Feel free to update these colors manually and remove these comments.
active_tab_foreground   #131a16
active_tab_background   #a6e3a1
inactive_tab_foreground #93a598
inactive_tab_background #1a231e
# END_AUTOGENERATED_TAB_STYLE
