[main]
font=JetBrainsMono Nerd Font:size=12
dpi-aware=yes
prompt="❯ "
icon-theme=Papirus-Dark
width=35
lines=10
horizontal-pad=20
vertical-pad=15
inner-pad=10

[colors]
# forest palette, background same as in kitty
background=131a16ee
text=cddbd0ff
prompt=a6e3a1ff
placeholder=64766aff
input=cddbd0ff
match=59c2a5ff
selection=223029dd
selection-text=e0ece2ff
selection-match=e3c078ff
border=a6e3a1ff

[border]
width=2
radius=12
